apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: docker.io/tmaxcloudck/example-order:yjh
        name: order
        ports:
        - containerPort: 80
